### ISSUE TITLE
Failed to download mono wasm SDK during build

### ISSUE THREAD

**Issue by oakrefactory** [nventive/Uno.Wasm.Bootstrap#29]
When creating an Uno app in Visual Studio, and building de related Wasm project, I get an error that the download of the mono wasm SDK failed. 
1>UnoApp.Wasm -> C:\Users\xxx\source\repos\UnoApp\UnoApp\UnoApp.Wasm\bin\Debug\netstandard2.0\UnoApp.Wasm.dll
1>Downloading mono-wasm-f07691d5125 to C:\Users\xxx\AppData\Local\Temp\mono-wasm-f07691d5125.zip
1>C:\Users\xxx\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.58\build\Uno.Wasm.Bootstrap.targets(33,3): error : InvalidOperationException: Failed to download the mono-wasm SDK at https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/598/Azure/processDownloadRequest/598/ubuntu-1804-amd64/sdks/wasm/mono-wasm-f07691d5125.zip
1>C:\Users\xxx\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.58\build\Uno.Wasm.Bootstrap.targets(33,3): error :

Running Visual Studio as administrator didn't help. Downloading the zip file through a browser is not a problem.

**Comment by jeromelaban** [comment]
Thanks for the report! Are you located behind a proxy by any chance ?

**Comment by oakrefactory** [comment]
Yes

**Comment by zwcloud** [comment]
Also it blocks visual studio from cancelling the building:

> 1>UnoWasmDemo -> D:\Workspace\0_Experiment\UnoWasmDemo\UnoWasmDemo\bin\Debug\netstandard2.0\UnoWasmDemo.dll
> 1>Downloading mono-wasm-f07691d5125 to C:\Users\cloud\AppData\Local\Temp\mono-wasm-f07691d5125.zip
> 1>C:\Users\cloud\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.58\build\Uno.Wasm.Bootstrap.targets(33,3): warning MSB4220: Waiting for the currently executing task "ShellTask_vd5144dd11cb6254c50778bbaeb2cb9065b305ef9" to cancel.

I think the downloading task should have a timeout setting or able to cancelled manually. BTW, can we use a local [mono-wasm SDK](https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/obtain-wasm-sdk.md#download-webassembly-sdk) that has already been downloaded? The network speed could be very slow for some special region such as China.

**Comment by jeromelaban** [comment]
@zwcloud sure, this deployment model is very weak for sure. It's temporary though, until the mono team gets their deployment model finalized. We can definitely change the source to be local instead of a download, for sure. That being said, I'm waiting for https://github.com/mono/mono/pull/11724 and https://github.com/mono/mono/pull/11396 to be merged so I don't need to make ugly local adjustments to the mono-wasm packager.
