### ISSUE TITLE
Accessing C/C++ Libraries

### ISSUE THREAD

**Issue by MelbourneDeveloper** [nventive/Uno.Wasm.Bootstrap#36]
Sorry, but this is more of a question than an issue. I have a .NET Standard library that accesses a Windows DLL called Hid.dll. I would like to try to get this library working on Wasm with Platform Uno. I am naive about the limitations of Wasm. How would I start to figure out whether the library can be used at runtime? Does the browser somehow have to trust the library? Is there someone else I should be contacting about this?

Here is the error I'm getting:
![image](https://user-images.githubusercontent.com/16697547/49474835-d1ce1a80-f869-11e8-9649-dcb64c5e5f62.png)

**Comment by MelbourneDeveloper** [comment]
I plan to leverage libusb which I think is a cross platform USB library for Windows and Linux.

**Comment by MelbourneDeveloper** [comment]
I should add that Hid.dll is a standard Windows OS library. And, here is Hid.Net which is my C# library to leverage it https://github.com/MelbourneDeveloper/Hid.Net

**Comment by MelbourneDeveloper** [comment]
https://stackoverflow.com/questions/32223638/using-c-dlls-in-a-browser

**Comment by MelbourneDeveloper** [comment]
https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm

**Comment by MelbourneDeveloper** [comment]
I think the answer to my question is that the C library would need to be compiled to wasm. I think that Emscripten could do this, but the library's owner would need to do the work to get it ported.

**Comment by jeromelaban** [comment]
Indeed, your library would need to be compiled to WebAssembly, though two points:
- Your wasm library can only access what Javascript can, meaning that if you use specific features that use Windows APIs, those won't be available.
- Dynamic linking is not yet available to mono-wasm build projects. The way to do it for now is to do something similar to https://github.com/nventive/Uno.SQLitePCLRaw.Wasm/blob/master/src/SQLitePCLRaw.provider.wasm/SQLite3Provider_WebAssembly.cs

I'll close this issue as this is more of a WebAssembly issue than a Uno wasm boostrapper issue.

**Comment by MelbourneDeveloper** [comment]
@jeromelaban , I checked this out: https://github.com/nventive/Uno.sqlite-wasm . Just so I understand this correctly, this library uses the sqlite3 C library. Does the wasm environment allow linking to this DLL simply because browsers are shipped with this library, and they trust it? Or, is there something I'm missing in my understanding there?
