### ISSUE TITLE
Error building with latest NuGet

### ISSUE THREAD

**Issue by MarcosCobena** [nventive/Uno.Wasm.Bootstrap#42]
Hey @jeromelaban,

The latest NuGet (139) must be somewhat broken because of this output:

`/Users/marcos/.nuget/packages/uno.wasm.bootstrap/1.0.0-dev.139/build/Uno.Wasm.Bootstrap.targets(3,3): Error MSB4019: The imported project "/Users/marcos/.nuget/packages/uno.wasm.bootstrap/1.0.0-dev.139/build/Uno.Wasm.Bootstrap.Publish.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. (MSB4019) (WebAssemblyWebGLDemo)`

Such file's actually named `Uno.Wasm.Bootstrap.targets`.

Thanks for your work on this :-)

—Marcos

**Comment by MarcosCobena** [comment]
137 builds just fine :-)

**Comment by jeromelaban** [comment]
Thanks for the report!

Yes, indeed, the files in the nuget package were incorrectly included, resulting in an broken build using the nuget package (something the CI does not catch).

**Comment by MarcosCobena** [comment]
Thanks for the super quick response :-)
