### ISSUE TITLE
Calling static methods

### ISSUE THREAD

**Issue by PadreSVK** [nventive/Uno.Wasm.Bootstrap#86]
Hi, I am playing with Uno.Wasm.Bootstrap, it is really nice project 👍 
I have problem with calling static method and FullAOT.
My c# code (namespace WasmSample)
 ```csharp
class InitClass
  {
        static void Main(string[] args) => Console.WriteLine("Hello from C#!");
        static void Test(string[] args) => Console.WriteLine($"test static method");
 }
 ```
When I am calling from js these static methods 
 ```javascript
BINDING.call_static_method("[WasmSample] WasmSample.InitClass:Main", []); //this one works
BINDING.call_static_method("[WasmSample] WasmSample.InitClass:Test", []); //error
 ```
I recieve this error:
 ```javascript
    Uncaught Error: Could not find method: Test
    at Object.resolve_method_fqn (mono.js:8179)
    at Object.call_static_method (mono.js:8184)
    at <anonymous>:1:9
 ```
Please, could you explain me, why is it possible to call only Main method? Is it some restriction?

**Comment by jeromelaban** [comment]
Thanks :) This may be related to the linker. Can you ensure that the [main assembly is excluded](https://github.com/nventive/Uno.Wasm.Bootstrap#linker-configuration-1) ?

**Comment by PadreSVK** [comment]
🤦‍♂️ thank you very much, that was a problem 😊
 So I supposed that every assembly in LinkerConfig was not affected by treeshaking? And every (code) file in managed* folder is excluded similar rule.
Or if I am wrong, could you please explain me how it works?
